# Deployment Definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarker-apii
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmarker-apii
  template:
    metadata:
      labels:
        app: bookmarker-apii
    spec:
      containers:
        - name: bookmarker-apii
          image: bookmarker-apii:1.2  # Use the image you tagged
          ports:
            - containerPort: 8080

---
# Service Definition
apiVersion: v1
kind: Service
metadata:
  name: bookmarker-apii-service
spec:
  selector:
    app: bookmarker-apii
  ports:
    - protocol: TCP
      port: 8080           # Internal Kubernetes port (the port inside the cluster)
      targetPort: 8080     # The container's port
      nodePort: 30087      # External port on each node that will be used to access the service
  type: NodePort          # Exposes the service externally via NodePort
